baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
title = "Hugo Blog Template for GitHub Pages"
canonifyurls = true
